version: "2"
services:
  app:
    container_name: app
    build: .
    ports:
      - '3030:3030'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
